---
# tasks file for CIS-Ubuntu-Linux-16.04-LTS-Benchmark

- include: preliminary-checks.yml

- include: initial-setup.yml
    when: initial-setup

- include: services.yml
    when: services

- include: network-configuration.yml
    when: network-configuration

- include: logging-and-auditing.yml
    when: logging-and-auditing

- include: access-authentication-and-authorizatoin.yml
    when: access-authentication-and-authorizatoin

- include: system-maintenance.yml
    when: system-maintenance
  