---

# tasks file for CIS-Ubuntu-Linux-16.04-LTS-Benchmark

- include: preliminary_checks.yml

- include: 1_initial_setup.yml
  when: initial_setup

- include: 2_services.yml
  when: services

- include: 3_network_configuration.yml
  when: network_configuration

- include: 4_logging_and_auditing.yml
  when: logging_and_auditing

- include: 5_access_authentication_and_authorization.yml
  when: access_authentication_and_authorization

- include: 6_system_maintenance.yml
  when: system_maintenance

- include: extras.yml
  when: extras
