---

### Below needs to be review for proper disabling procedure ###

- stat:
    path: /etc/inetd.conf
  register: inetd_conf
  failed_when: False
  ignore_errors: True
  changed_when: False

- stat:
    path: /etc/xinetd.conf
  register: xinetd_conf
  failed_when: False
  ignore_errors: True
  changed_when: False

- stat:
    path: /etc/inetd.d/chargen
  register: inetd_chargen
  failed_when: False
  ignore_errors: True
  changed_when: False

- stat:
    path: /etc/xinetd.d/chargen
  register: xinetd_chargen
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  lineinfile:
    dest: /etc/inetd.conf
    # Missing: Comment out or remove any lines starting with chargen from /etc/inetd.conf and /etc/inetd.d/*. 
  when: inetd_conf.stat.exists

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  lineinfile:
    dest: /etc/inetd.d/chargen
      # Missing: Comment out or remove any lines starting with chargen from /etc/inetd.conf and /etc/inetd.d/*. 
  when: inetd_chargen.stat.exists

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.conf
      # Missing: Comment out or remove any lines starting with chargen from /etc/xinetd.conf
  when: xinetd_conf.stat.exists

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/chargen
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: xinetd_chargen.stat.exists

### Missing benchmarks ###

- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  apt:
    name: "{{ time_sync_package }}"
    state: present

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  lineinfile:
    dest: "{{ item.name }}"
    regexp: '{{ item.expression }}'
    line: '{{ item.value }}'
  with_items:
    - { name: '/etc/ntp.conf' , expression: '^server' , value: 'pool {{ time_sync_server }}' }
    - { name: '/etc/ntp.conf' , expression: '^restrict -4' , value: 'restrict -4 default kod nomodify notrap nopeer noquery' }
    - { name: '/etc/ntp.conf' , expression: '^restrict -6' , value: 'restrict -6 default kod nomodify notrap nopeer noquery' }
    - { name: '/etc/init.d/ntp', expression: '^RUNASUSER' , value: 'RUNASUSER=ntp' }
  when: time_sync_package  == "ntp"
  notify: restart ntp

- name: 2.2.1.3 Ensure chrony is configured (Scored)
  lineinfile:
    dest: "{{ item.name }}"
    regexp: '{{ item.expression }}'
    line: '{{ item.value }}'
  with_items:
    - { name: '/etc/chrony/chrony.conf', expression: '^server', value: 'server {{ time_sync_server }}' }
    - { name: '/etc/chrony/chrony.conf', expression: '^pool', value: '' }
  when: time_sync_package  == "chrony"
  notify: restart chrony

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  apt:
    name: xserver-xorg-core*
    purge: yes
    state: absent

- command: dpkg-query -s avahi-daemon
  register: avahi_daemon
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.3 Ensure Avahi Server is not enabled (Scored)
  service:
    name: avahi-daemon
    state: stopped
    enabled: no
  when: avahi_daemon.rc == 0

- command: dpkg-query -s cups-server-common
  register: cups_server
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.4 Ensure CUPS is not enabled (Scored)
  service:
    name: cups
    state: stopped
    enabled: no
  when: cups_server.rc == 0

- command: dpkg-query -s isc-dhcp-server
  register: dhcp_server
  failed_when: False 
  ignore_errors: True
  changed_when: False

- command: dpkg-query -s isc-dhcp-server6
  register: dhcp6_server
  failed_when: False 
  ignore_errors: True
  changed_when: False

- name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - isc-dhcp-server
    - isc-dhcp-server6
  when: dhcp_server.rc == 0 or dhcp6_server.rc == 0

- command: dpkg-query -s slapd
  register: slapd
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.6 Ensure LDAP server is not enabled (Scored)
  service:
    name: slapd
    state: stopped
    enabled: no
  when: slapd.rc == 0

- command: dpkg-query -s nfs-kernel-server
  register: nfs_server
  failed_when: False
  ignore_errors: True
  changed_when: False

- command: dpkg-query -s rpcbind
  register: rpcbind
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - rpcbind
    - nfs-server
  when: nfs_server.rc == 0 or rpcbind.rc == 0

- command: dpkg-query -s bind9
  register: bind9
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.8 Ensure DNS Server is not enabled (Scored)
  service:
    name: bind9
    state: stopped
    enabled: no
  when: bind9.rc == 0

- command: dpkg-query -s vsftpd
  register: vsftpd
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.9 Ensure FTP Server is not enabled (Scored)
  service:
    name: vsftpd
    state: stopped
    enabled: no
  when: vsftpd.rc == 0

- command: dpkg-query -s apache2
  register: apache2
  failed_when: False 
  ignore_errors: True
  changed_when: False

- name: 2.2.10 Ensure HTTP server is not enabled (Scored) 
  service:
    name: apache2
    state: stopped
    enabled: no
  when: apache2.rc == 0

- command: dpkg-query -s dovecot
  register: dovecot
  failed_when: False
  ignore_errors: True
  changed_when: False

- command: dpkg-query -s exim
  register: exim
  failed_when: False
  ignore_errors: True
  changed_when: False

- command: dpkg-query -s cyrus-imap
  register: cyrus_imap
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - dovecot
    - exim
    - cyrus-imap
  when: dovecot.rc == 0 or exim.rc == 0 or cyrus_imap.rc == 0

- command: dpkg-query -s smbd
  register: smbd
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.12 Ensure Samba is not enabled (Scored)
  service:
    name: smbd
    state: stopped
    enabled: no
  when: smbd.rc == 0

- command: dpkg-query -s squid
  register: squid
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
  service:
    name: squid
    state: stopped
    enabled: no
  when: squid.rc == 0

- command: dpkg-query -s snmpd
  register: snmpd
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
  service:
    name: snmpd
    state: stopped
    enabled: no
  when: snmpd.rc == 0

- apt:
    name: postfix
    state: present

- name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^inet_interfaces'
    line: 'inet_interfaces = localhost'
    state: present
    create: no
  notify: restart postfix

- command: dpkg-query -s rsync
  register: rsync
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.16 Ensure rsync service is not enabled (Scored)
  service:
    name: rsync
    state: stopped
    enabled: no
  when: rsync.rc == 0

- command: dpkg-query -s nis
  register: nis
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: 2.2.17 Ensure NIS Server is not enabled (Scored)
  service:
    name: nis
    state: stopped
    enabled: no
  when: nis.rc == 0

- name: 2.3.1 Ensure NIS Client is not installed (Scored)
  apt:
    name: nis
    state: absent

- name: 2.3.2 Ensure rsh client is not installed (Scored)
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - rsh-client
    - rsh-redone-client

- name: 2.3.3 Ensure talk client is not installed (Scored)
  apt:
    name: talk
    state: absent

- name: 2.3.4 Ensure telnet client is not installed (Scored)
  apt:
    name: telnet
    state: absent

- name: 2.3.5 Ensure LDAP client is not installed (Scored)
  apt:
    name: ldap-utils
    state: absent
